apiVersion: v1
kind: Service
metadata:
  annotations:
    io.elastest: "true"
  creationTimestamp: null
  labels:
    io.elastest: "true"
    io.elastest.service: full-teaching-service
    io.elastest.service.type: SUT
  name: full-teaching-service
spec:
  ports:
  - name: "full-teaching-5001-node-port"
    port: 5001
    targetPort: 5001
    nodePort: 5001 
  selector:
    io.elastest.service: full-teaching
  type: NodePort
status:
  loadBalancer: {}
